services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=overmods'
      - 'POSTGRES_PASSWORD=overmods'
      - 'POSTGRES_USER=overmods'
    ports:
      - '5432'
  redis:
    image: 'redis:7.2.4-alpine'
    volumes:
      - redis_data:/data
    ports:
      - '6379'
volumes:
  redis_data:
    driver: local