apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: overmods
spec:
  selector:
    matchLabels:
      app: overmods
      service: backend
  serviceName: backend
  template:
    metadata:
      labels:
        app: overmods
        service: backend
    spec:
      containers:
        - image: mykola2312/overmods-backend:v0.1.0
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8080
          env:
            - name: OVERMODS_DATA_PATH
              value: "/var/lib/backend-data"
#          volumeMounts:
#            - mountPath: /var/lib/backend-data
#              name: backend-data
#  volumeClaimTemplates:
#    - metadata:
#        name: backend-data
#      spec:
#        accessModes: [ "ReadWriteMany" ]
#        resources:
#          requests:
#            storage: 128Mi
