apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: overmods
spec:
  selector:
    app: overmods
    service: backend
  type: ClusterIP
  ports:
    - name: backend
      protocol: TCP
      port: 8080