apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: overmods
spec:
  selector:
    matchLabels:
      app: overmods
      service: db
  serviceName: db
  template:
    metadata:
      labels:
        app: overmods
        service: db
    spec:
      containers:
        - image: postgres:alpine
          name: db
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: overmods
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgres
              name: db-data
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi
