apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: overmods
spec:
  selector:
    app: overmods
    service: db
  type: ClusterIP
  ports:
    - name: db
      protocol: TCP
      port: 5432