apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: overmods
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/overmods-data"